### PR TITLE
Fix : Separate cluster into categories

### LINKED ISSUE #91: Move deleted cluster to bottom
In cluster Listing we need to move the deleted clusters to the bottom

### PR DESCRIPTION
**Pull request by jyash97**
Fix #91

### CODE REVIEW

**Comment by siddharthlatest** [comment]
lgtm 👍

File: src/pages/ClusterPage/ClusterPage.js [hunk 1]
```diff
@@ -154,72 +225,43 @@ export default class ClusterPage extends Component {
...
-											</div>
-										</div>
-									</li>
-								))}
-							</ul>
+              <h2>My Clusters</h2>
+
+              {this.renderClusterHeading('Active Clusters', activeClusters.length)}
+              {
+                activeClusters.length ? (
```
Comment (metagrover) [inline src/pages/ClusterPage/ClusterPage.js]: Linting issues - we use tabs of width 4 everywhere. Please fix this.
